name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: yhucao/TTS-Mandarin@main
        with:
          text: '测试'
          voice: '18'
          content: 'out.mp3'
      - run: pwd 
